version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.1.7

workflows:
  multiple-ghc-build:
    jobs:

      - haskell/build-with-binary-cache:
          name: GHC 8.0.2
          executor: haskell/ghc-8_2_2
          context: haskell-ci
          run-check: false
          fail-incoherent-builds: false
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --test-options='+RTS -g1'

      - haskell/build-with-binary-cache:
          name: GHC 8.2.2
          executor: haskell/ghc-8_2_2
          context: haskell-ci
          run-check: false
          fail-incoherent-builds: false
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --test-options='+RTS -g1'

      - haskell/build-with-binary-cache:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          context: haskell-ci
          run-check: false
          fail-incoherent-builds: false
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --test-options='+RTS -g1'

      - haskell/build-with-binary-cache:
          name: GHC 8.8.3
          executor: haskell/ghc-8_8_3
          context: haskell-ci
          run-check: false
          fail-incoherent-builds: false
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --test-options='+RTS -g1'

      - haskell/build-with-binary-cache:
          name: GHC 8.10.1
          executor: haskell/ghc-8_10_1
          context: haskell-ci
          run-check: false
          fail-incoherent-builds: false
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --test-options='+RTS -g1'
